apiVersion: v1
kind: Service
metadata:
  name: spark-srv
spec:
  selector:
    app: sparkmaster
  ports:
  - protocol: TCP
    name: port1
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: port2
    port: 7077
    targetPort: 7077
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkmaster-deployment
  labels:
    app: sparkmaster
spec:
  selector:
    matchLabels:
      app: sparkmaster
  template:
    metadata:
      labels:
        app: sparkmaster
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: jars-dir
        emptyDir: {}
      initContainers:
      - name: compileapp
        image: jaavier8/predictork8s
        volumeMounts:
        - name: shared-data
          mountPath: /opt/spark-apps
      containers:
      - name: sparkmaster
        image: bitnami/spark:3.1.2-debian-10-r130
        lifecycle:
          postStart:
            exec:
              command: [ 'bin/sh', '-c', 'spark-submit --conf spark.jars.ivy=/opt/bitnami/spark/ivy --master k8s://localhost:7077 --deploy-mode cluster --supervise --class es.upm.dit.ging.predictor.MakePrediction --name FlightPrediction --packages org.mongodb.spark:mongo-spark-connector_2.12:3.0.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 /opt/spark-apps/practicaBD/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar' ]
        ports:
        - containerPort: 8080
        - containerPort: 7077
        volumeMounts:
        - name: shared-data
          mountPath: /opt/spark-apps
        - name: jars-dir
          mountPath: /opt/bitnami/spark/ivy
        env:
        - name: SPARK_MODE
          value: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkworker-deployment
  labels:
    app: sparkworker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sparkworker
  template:
    metadata:
      labels:
        app: sparkworker
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: jars-dir
        emptyDir: {}
      initContainers:
      - name: compileapp
        image: jaavier8/predictork8s
        volumeMounts:
        - name: shared-data
          mountPath: /opt/spark-apps
      containers:
      - name: sparkworker
        image: bitnami/spark:3.1.2-debian-10-r130
        ports:
        - containerPort: 8080
        - containerPort: 7077
        volumeMounts:
        - name: shared-data
          mountPath: /opt/spark-apps
        - name: jars-dir
          mountPath: /opt/bitnami/spark/ivy
        env:
        - name: SPARK_MODE
          value: worker
        - name: SPARK_MASTER_URL
          value: spark-srv:7077
        - name: SPARK_WORKER_MEMORY
          value: 1G
        - name: SPARK_WORKER_CORES
          value: '2'
