apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: predictor
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: jaavier8/test5
  mainClass: es.upm.dit.ging.predictor.MakePrediction
  mainApplicationFile: "local:///opt/spark-apps/practicaBD/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar"
  sparkVersion: "3.1.2"
  deps:
    jars:
      - local:///opt/spark-apps/jars/com.github.luben_zstd-jni-1.4.8-1.jar
      - local:///opt/spark-apps/jars/org.apache.commons_commons-pool2-2.6.2.jar
      - local:///opt/spark-apps/jars/org.apache.kafka_kafka-clients-2.6.0.jar
      - local:///opt/spark-apps/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.1.2.jar
      - local:///opt/spark-apps/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.1.2.jar
      - local:///opt/spark-apps/jars/org.lz4_lz4-java-1.7.1.jar
      - local:///opt/spark-apps/jars/org.mongodb_bson-4.0.5.jar
      - local:///opt/spark-apps/jars/org.mongodb_mongodb-driver-core-4.0.5.jar
      - local:///opt/spark-apps/jars/org.mongodb_mongodb-driver-sync-4.0.5.jar
      - local:///opt/spark-apps/jars/org.mongodb.spark_mongo-spark-connector_2.12-3.0.1.jar
      - local:///opt/spark-apps/jars/org.slf4j_slf4j-api-1.7.30.jar
      - local:///opt/spark-apps/jars/org.spark-project.spark_unused-1.0.0.jar
      - local:///opt/spark-apps/jars/org.xerial.snappy_snappy-java-1.1.8.2.jar
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    labels:
      version: 3.1.2
    serviceAccount: default
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    labels:
      version: 3.1.2
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
