apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: predictor
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: jaavier8/k8spred
  mainClass: es.upm.dit.ging.predictor.MakePrediction
  mainApplicationFile: "local:///opt/spark-apps/practicaBD/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar"
  sparkVersion: "3.1.2"
  volumes:
    - name: shared-data
      emptyDir: {}
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.2
    serviceAccount: default
    initContainers:
    - name: compileapp
      image: jaavier8/k8spred
      volumeMounts:
      - name: shared-data
        mountPath: /opt/spark-apps
    volumeMounts:
      - name: shared-data
        mountPath: /opt/spark-apps
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.2
    initContainers:
    - name: compileapp
      image: jaavier8/k8spred
      volumeMounts:
      - name: shared-data
        mountPath: /opt/spark-apps
    volumeMounts:
      - name: shared-data
        mountPath: /opt/spark-apps